version: 2.1
orbs:
  architect: giantswarm/architect@0.8.6

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-default-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "loadtest-app"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
